### PR TITLE
Added Encapsulation code and documentation

### PR DESCRIPTION
**Pull request by DanDias00**

### CODE REVIEW

**Comment by buddhikac96** [comment]
@DanDias00 This is great. Please also explain your code in the documentation.

**Comment by DanDias00** [comment]
> @DanDias00 This is great. Please also explain your code in the documentation.

Hi @buddhikac96 I have made the necessary changes as requested:)

**Comment by buddhikac96** [comment]
@DanDias00 Great. Now, this is almost over. Would it be possible to highlight code snippets in the documentation as well? Refer to this link.

https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by DanDias00** [comment]
> @DanDias00 Great. Now, this is almost over. Would it be possible to highlight code snippets in the documentation as well? Refer to this link.
> 
> https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Hi @buddhikac96 I have made the necessary changes

**Comment by buddhikac96** [comment]
@DanDias00 This looks awesome. This is mergeable to the master. Thank you for the code!

**Pull request merged**
